name: "Deploy AWS Stack"
description: "Create or updates an AWS stack using CloudFormation"
inputs:
  stack-name:
    description: "The Stack Name"
    required: true
  template-file:
    description: "The CloudFormation template file with the resources to be created"
    required: true
  user-password:
    description: "Password for the user to be created"
    required: true
  aws-region:
    description: "AWS region where the stack will be created"
    required: true
  dry-run:
    description: "Enable test the template before creating the stack"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
